### ISSUE TITLE
run_rnaseqc.py issue

### ISSUE THREAD

**Issue by methionine-Z** [broadinstitute/gtex-pipeline#11]
Hello, I am testing and received below message. How should I try to fix this? Thank you for the help!

mz@mz:$ docker run --rm -v /RNA:/data -t rnatest:V1 /bin/bash -c "/src/run_rnaseqc.py K.Aligned.sortedByCoord.out.patched.md.bam gencode.v19.chr_patch_hapl_scaff.annotation.patched.gtf Homo_sapiens_assembly19.fasta K --output_dir /data"
[Aug 02 18:40:03] Running RNA-SeQC
  * command: "java -Xmx4g -jar /opt/RNA-SeQC_1.1.9/RNA-SeQC.jar -n 1000 -s K,K.Aligned.sortedByCoord.out.patched.md.bam,K -t gencode.v19.chr_patch_hapl_scaff.annotation.patched.gtf -r Homo_sapiens_assembly19.fasta -o /data -noDoC -strictMode -gatkFlags --allow_potentially_misencoded_quality_scores"
RNA-SeQC v1.1.9 06/26/16
Additional GATK flags provided: --allow_potentially_misencoded_quality_scores
Creating rRNA Interval List based on given GTF annotations
Retriving contig names from reference
	 contig names in reference: 85
Loading GTF for Read Counting
Converting to refGene
Transcript objects to RefGen format:	2 s
Running IntronicExpressionReadBlock Walker ....
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.<init>(GenomeAnalysisEngine.java:160)
	at org.broadinstitute.sting.gatk.CommandLineExecutable.<init>(CommandLineExecutable.java:53)
	at org.broadinstitute.sting.gatk.CommandLineGATK.<init>(CommandLineGATK.java:54)
	at org.broadinstitute.cga.rnaseq.gatk.GATKTools.runIntronReadCount(GATKTools.java:203)
	at org.broadinstitute.cga.rnaseq.ReadCountMetrics.runRegionCounting(ReadCountMetrics.java:220)
	at org.broadinstitute.cga.rnaseq.ReadCountMetrics.runReadCountMetrics(ReadCountMetrics.java:59)
	at org.broadinstitute.cga.rnaseq.RNASeqMetrics.runMetrics(RNASeqMetrics.java:211)
	at org.broadinstitute.cga.rnaseq.RNASeqMetrics.execute(RNASeqMetrics.java:162)
	at org.broadinstitute.cga.rnaseq.RNASeqMetrics.main(RNASeqMetrics.java:133)
Caused by: java.lang.NullPointerException
	at org.reflections.Reflections.scan(Reflections.java:220)
	at org.reflections.Reflections.scan(Reflections.java:166)
	at org.reflections.Reflections.<init>(Reflections.java:94)
	at org.broadinstitute.sting.utils.classloader.PluginManager.<clinit>(PluginManager.java:77)
	... 9 more
Traceback (most recent call last):
  File "/src/run_rnaseqc.py", line 102, in <module>
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'java -Xmx4g -jar /opt/RNA-SeQC_1.1.9/RNA-SeQC.jar -n 1000 -s K,K.Aligned.sortedByCoord.out.patched.md.bam,K -t gencode.v19.chr_patch_hapl_scaff.annotation.patched.gtf -r Homo_sapiens_assembly19.fasta -o /data -noDoC -strictMode -gatkFlags --allow_potentially_misencoded_quality_scores' returned non-zero exit status 1

**Comment by methionine-Z** [comment]
Very sorry that I forgot to close this. 1.7 worked. Is there a simpler way to set java environment in docker image? Thank you @francois-a

**Comment by 52-hertz-whale** [comment]
Hello, I got the same problem. Could you tell me how to set java version in docker?

**Comment by methionine-Z** [comment]
Switch your java to 1.7 will work.

**Comment by francois-a** [comment]
You can specify the java version as shown here:
https://github.com/broadinstitute/gtex-pipeline/blob/master/rnaseq/rnaseqc_counts.wdl#L21

**Comment by 52-hertz-whale** [comment]
Thanks, It works

**Comment by shintzen** [comment]
Isn't Java 1.7 a security risk? I don't think you can install it from Oracle anymore. How is this going to be supported going forward?
https://askubuntu.com/questions/761127/how-do-i-install-openjdk-7-on-ubuntu-16-04-or-higher

**Comment by ljmills** [comment]
I am also having this issue and the link in the previous post for how to change the version of java in the image isn't working. Can someone share how they pointed RNA-SeQC to java 1.7?

**Comment by francois-a** [comment]
We are no longer supporting v1 of RNA-SeQC. Please take a look at the new version here: https://github.com/getzlab/rnaseqc.
