### ISSUE TITLE
questions about counts_gct file and sample_participant_lookup file in eQTL

### ISSUE THREAD

**Issue by 11612606** [broadinstitute/gtex-pipeline#24]
Hi,

I'm working on the first step of eQTL pipeline. In the RNA-Seq pipeline, I've aggregated the gene_tpm.gct files of all samples into one tpm.gct file. When generating normalized expression in BED format, which tpm.gct file should I use, the one of each sample or the combined one?

And the sample_participant_lookup file I've generated is showed in the following figure. I am not sure about the format. Is this right?

<img width="667" alt="image" src="https://user-images.githubusercontent.com/42996649/52853611-170aa480-3157-11e9-8990-3d979041ebc6.png">

When I run the following command, I got this error. How can I fix this error?

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/42996649/52853298-263d2280-3156-11e9-99b8-9ff14c7d78b3.png">

Thanks!

**Comment by francois-a** [comment]
The order of the lookup file needs to be reversed: samples -> participants

**Comment by 11612606** [comment]
I have reversed the lookup file, but when I try again, I still got the same IndexError. Could you tell me how can I fix this error? Thank you!
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/42996649/52914363-5295a200-3302-11e9-9cbf-1b091390edf6.png">

**Comment by hnaeem** [comment]
I'm getting the same error: 
Loading expression data
Normalizing data (tmm)
Traceback (most recent call last):
  File "/src/eqtl_prepare_expression.py", line 177, in <module>
    sample_participant_lookup_s = pd.read_csv(args.sample_participant_lookup, sep='\t', index_col=0, dtype=str, squeeze=True)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/gpfs/projects/SDR_transcriptomics_ymokrab/genotype/eQTL/input/input_1076/GTExsample_participant_lookup.csv' does not exist

Any help will be appreciated

**Comment by 11612606** [comment]
Sorry to reply late!


The look_up file looks like this

SRR1309070      GTEX-1117F

SRR1309248      GTEX-1117F

SRR1500555      GTEX-1117F

SRR1307808      GTEX-111CU

SRR1308269      GTEX-111CU

SRR1309032      GTEX-111CU




The chromosome_list looks likes this(same as the chromosome name in the gtf file)

chr1

chr2

chr3

chr4




Hear is my command

python eqtl_prepare_expression.py rnaseqc_tpm.gct rnaseqc_gene_reads.gct gencode.v19.genes.gtf \

lookup.csv vcf_chr_list.txt ./out  \

--tpm_threshold 0.1 \

--count_threshold 6 \

--sample_frac_threshold 0.2 \



--normalization_method tmm




I hope that's helpful~




------------------ 原始邮件 ------------------
发件人: "Haroon"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 晚上7:07
收件人: "broadinstitute/gtex-pipeline"<gtex-pipeline@noreply.github.com>;
抄送: "毛毛"<2043053390@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [broadinstitute/gtex-pipeline] questions about counts_gct fileand sample_participant_lookup file in eQTL (#24)




I'm getting the same error:
 Loading expression data
 Normalizing data (tmm)
 Traceback (most recent call last):
 File "/src/eqtl_prepare_expression.py", line 177, in 
 sample_participant_lookup_s = pd.read_csv(args.sample_participant_lookup, sep='\t', index_col=0, dtype=str, squeeze=True)
 File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 678, in parser_f
 return _read(filepath_or_buffer, kwds)
 File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 440, in _read
 parser = TextFileReader(filepath_or_buffer, **kwds)
 File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 787, in init
 self._make_engine(self.engine)
 File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1014, in _make_engine
 self._engine = CParserWrapper(self.f, **self.options)
 File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1708, in init
 self._reader = parsers.TextReader(src, **kwds)
 File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.cinit
 File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
 FileNotFoundError: File b'/gpfs/projects/SDR_transcriptomics_ymokrab/genotype/eQTL/input/input_1076/GTExsample_participant_lookup.csv' does not exist
 
Any help will be appreciated

**Comment by AdrielleM** [comment]
> I have reversed the lookup file, but when I try again, I still got the same IndexError. Could you tell me how can I fix this error? Thank you!
> <img alt="image" width="1439" src="https://user-images.githubusercontent.com/42996649/52914363-5295a200-3302-11e9-9cbf-1b091390edf6.png">

I have this same error, someone managed to solve ?

**Comment by maegsul** [comment]
I have the same error too. Any solution? @francois-a
