### ISSUE TITLE
Error at run _rnaseq.py

### ISSUE THREAD

**Issue by nelsonchanhk** [broadinstitute/gtex-pipeline#52]
Hello, I am stuck at the run_rnaseq.py step while following the suggested v8 pipeline with docker. All the reference gtf/fasta were obtained from the recommended source on the GitHub page. Have I missed out something? Thank you very much!

nelson@hemepath:~/OPERATION/GTEX/data/star_out$ docker run --rm -v $path_to_data:/data -t broadinstitute/gtex_rnaseq:V8     /bin/bash -c "/src/run_rnaseqc.py \
    ${sample_id}.Aligned.sortedByCoord.out.patched.md.bam \
    ${genes_gtf} \
    ${genome_fasta} \
    ${sample_id} \
    --java /usr/lib/jvm/java-1.7.0-openjdk-amd64/bin/java \
    --output_dir /data"
[Nov 25 10:10:12] Running RNA-SeQC
  * command: "/usr/lib/jvm/java-1.7.0-openjdk-amd64/bin/java -Xmx4g -jar /opt/RNA-SeQC_1.1.9/RNA-SeQC.jar -n 1000 -s HA10YLS,HA10YLS.Aligned.sortedByCoord.out.patched.md.bam,HA10YLS -t GENCODE_gencode.v26.GRCh38.annotation.gtf -r references_Homo_sapiens_assembly38_noALT_noHLA_noDecoy.fasta -o /data -noDoC -strictMode -gatkFlags --allow_potentially_misencoded_quality_scores"
RNA-SeQC v1.1.9 06/26/16
Additional GATK flags provided: --allow_potentially_misencoded_quality_scores
Creating rRNA Interval List based on given GTF annotations
Retriving contig names from reference
         contig names in reference: 195
Loading GTF for Read Counting
The required transcript_id attribute was not found on line chr1 HAVANA  gene    11869   14409   .       +       .       gene_id "ENSG00000223972.5"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; level 2; havana_gene "OTTHUMG00000000961.2";
Traceback (most recent call last):
  File "/src/run_rnaseqc.py", line 102, in <module>
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/lib/jvm/java-1.7.0-openjdk-amd64/bin/java -Xmx4g -jar /opt/RNA-SeQC_1.1.9/RNA-SeQC.jar -n 1000 -s HA10YLS,HA10YLS.Aligned.sortedByCoord.out.patched.md.bam,HA10YLS -t GENCODE_gencode.v26.GRCh38.annotation.gtf -r references_Homo_sapiens_assembly38_noALT_noHLA_noDecoy.fasta -o /data -noDoC -strictMode -gatkFlags --allow_potentially_misencoded_quality_scores' returned non-zero exit status 1

**Comment by francois-a** [comment]
Hi, this is likely because you're using the full instead of collapsed reference annotation. Please see [here](https://github.com/broadinstitute/gtex-pipeline/blob/master/TOPMed_RNAseq_pipeline.md); the GTFs are available on the GTEx Portal and at gs://gtex-resources/GENCODE/.

**Comment by nelsonchanhk** [comment]
Thank you @francois-a. The gtf issue is solved but it looks like I'm coming back to the java 1.7 issue again. The argument of --java /usr/lib/jvm/java-1.7.0-openjdk-amd64/bin/java was specified in the command but I had the CallProcessError. Would be most helpful if you can advise.

nelson@hemepath:~/OPERATION/GTEX/data$ docker run --rm -v $path_to_data:/data -t broadinstitute/gtex_rnaseq:V8 \
    ${genome_fasta} \
>     /bin/bash -c "/src/run_rnaseqc.py \
>     ${sample_id}.Aligned.sortedByCoord.out.patched.md.bam \
>     ${genes_gtf} \
>     ${genome_fasta} \
>     ${sample_id} \
>     --java /usr/lib/jvm/java-1.7.0-openjdk-amd64/bin/java \
>     --output_dir /data"
[Nov 25 23:17:02] Running RNA-SeQC
  * command: "/usr/lib/jvm/java-1.7.0-openjdk-amd64/bin/java -Xmx4g -jar /opt/RNA-SeQC_1.1.9/RNA-SeQC.jar -n 1000 -s HA10YLS,HA10YLS.Aligned.sortedByCoord.out.patched.md.bam,HA10YLS -t gencode.v30.GRCh38.ERCC.genes.collapsed_only.gtf -r references_Homo_sapiens_assembly38_noALT_noHLA_noDecoy.fasta -o /data -noDoC -strictMode -gatkFlags --allow_potentially_misencoded_quality_scores"
RNA-SeQC v1.1.9 06/26/16
Additional GATK flags provided: --allow_potentially_misencoded_quality_scores
Creating rRNA Interval List based on given GTF annotations
Retriving contig names from reference
         contig names in reference: 195
Loading GTF for Read Counting
Converting to refGene
Transcript objects to RefGen format:    1 s
Running IntronicExpressionReadBlock Walker ....
Arguments: [-T, IntronicExpressionReadBlockWalker, --outfile_metrics, /data/HA10YLS/HA10YLS, -R, references_Homo_sapiens_assembly38_noALT_noHLA_noDecoy.fasta, -I, HA10YLS.Aligned.sortedByCoord.out.patched.md.bam, -strict, -refseq, /data/refGene.txt, -l, ERROR, --allow_potentially_misencoded_quality_scores]
org.broadinstitute.sting.utils.exceptions.UserException$CouldNotReadInputFile: Couldn't read file /data/HA10YLS.Aligned.sortedByCoord.out.patched.md.bam because java.io.FileNotFoundException: HA10YLS.Aligned.sortedByCoord.out.patched.md.bam (No such file or directory)
        at org.broadinstitute.sting.gatk.datasources.reads.SAMDataSource$ReaderInitializer.call(SAMDataSource.java:1040)
        at org.broadinstitute.sting.gatk.datasources.reads.SAMDataSource$SAMReaders.<init>(SAMDataSource.java:896)
        at org.broadinstitute.sting.gatk.datasources.reads.SAMDataSource$SAMResourcePool.createNewResource(SAMDataSource.java:853)
        at org.broadinstitute.sting.gatk.datasources.reads.SAMDataSource$SAMResourcePool.getAvailableReaders(SAMDataSource.java:824)
        at org.broadinstitute.sting.gatk.datasources.reads.SAMDataSource.<init>(SAMDataSource.java:261)
        at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.createReadsDataSource(GenomeAnalysisEngine.java:855)
        at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.initializeDataSources(GenomeAnalysisEngine.java:759)
        at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.execute(GenomeAnalysisEngine.java:259)
        at org.broadinstitute.sting.gatk.CommandLineExecutable.execute(CommandLineExecutable.java:113)
        at org.broadinstitute.sting.commandline.CommandLineProgram.start(CommandLineProgram.java:237)
        at org.broadinstitute.sting.commandline.CommandLineProgram.start(CommandLineProgram.java:147)
        at org.broadinstitute.cga.rnaseq.gatk.GATKTools.runIntronReadCount(GATKTools.java:213)
        at org.broadinstitute.cga.rnaseq.ReadCountMetrics.runRegionCounting(ReadCountMetrics.java:220)
        at org.broadinstitute.cga.rnaseq.ReadCountMetrics.runReadCountMetrics(ReadCountMetrics.java:59)
        at org.broadinstitute.cga.rnaseq.RNASeqMetrics.runMetrics(RNASeqMetrics.java:211)
        at org.broadinstitute.cga.rnaseq.RNASeqMetrics.execute(RNASeqMetrics.java:162)
        at org.broadinstitute.cga.rnaseq.RNASeqMetrics.main(RNASeqMetrics.java:133)
RNA-SeQC Total Runtime: 0 min
Traceback (most recent call last):
  File "/src/run_rnaseqc.py", line 102, in <module>
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/lib/jvm/java-1.7.0-openjdk-amd64/bin/java -Xmx4g -jar /opt/RNA-SeQC_1.1.9/RNA-SeQC.jar -n 1000 -s HA10YLS,HA10YLS.Aligned.sortedByCoord.out.patched.md.bam,HA10YLS -t gencode.v30.GRCh38.ERCC.genes.collapsed_only.gtf -r references_Homo_sapiens_assembly38_noALT_noHLA_noDecoy.fasta -o /data -noDoC -strictMode -gatkFlags --allow_potentially_misencoded_quality_scores' returned non-zero exit status 3

**Comment by francois-a** [comment]
It looks like the problem is related to how you're linking the BAM file:
```
/data/HA10YLS.Aligned.sortedByCoord.out.patched.md.bam because java.io.FileNotFoundException: HA10YLS.Aligned.sortedByCoord.out.patched.md.bam (No such file or directory)
```

**Comment by nelsonchanhk** [comment]
@francois-a Got it working now. Thank you very much!
